### ISSUE TITLE
Add background-color for compose area

### ISSUE THREAD

**Issue by llamacucumber** [ronilaukkarinen/mastodon-bird-ui#10]
People on Veganism Social like Bird UI, but some have complained about the lack of a background-color for the new post text area.
I think making it a shade lighter or darker, instead of transparent, would be great to indicate where to click. 

One complaint:
https://veganism.social/@beforewisdom/110141454410372953

**Comment by ronilaukkarinen** [comment]
There will always be people who don't like some parts of the UI. I'm kinda fond of the left and right panels "floating around". I've enterntained myself earlier about the idea of the box having some outline, but it's too "boxy" in my taste with any borders or background colors:

![image](https://user-images.githubusercontent.com/1534150/230441648-747bdc1c-90fc-4262-93bd-572bf7065753.png)
![image](https://user-images.githubusercontent.com/1534150/230441717-416a0f3f-5819-40f4-996d-62e9f0c9dea0.png)

In overall picture there's something that is distracting this way, it jumps to your eyes:
![image](https://user-images.githubusercontent.com/1534150/230443291-5f89a9a7-7499-4c50-b8dd-3b903ae6acbd.png)

It's rather easy to add this to the end of your Custom CSS, if you want it, here:

```css
/* Add background color for the compose form */
/* stylelint-disable-next-line no-duplicate-selectors */
.layout-single-column .compose-form .compose-form__autosuggest-wrapper,
.layout-single-column .compose-form .compose-form__buttons-wrapper {
  background-color: var(--color-mud);
  border-color: var(--color-mud);
  padding-top: 0;
}

/* Fixes to bottom row when there's a background */
.layout-single-column .compose-form .compose-form__buttons-wrapper {
  padding-bottom: calc(var(--gap-default) / 2);
}
```

But for now I'm not going to add this as default.
