### ISSUE TITLE
Issues with Glitch-Soc theming

### ISSUE THREAD

**Issue by hmhackmaster** [ronilaukkarinen/mastodon-bird-ui#11]
I certainly know this is not a bug with your CSS, as your project targets the vanilla/standard Mastodon theming, but I figured I would create this to see if you have any pointers and for others who may be encountering the same issue.

For those unfamiliar, [Glitch-Soc](https://github.com/glitch-soc/mastodon/) is a fork of Mastodon that introduces some additional functionality. It's pretty popular and is used on a number of instances With regards to the `mastodon-bird-ui` CSS, the additional functionality that's causing issues is Glitch-Soc's [Theming System](https://glitch-soc.github.io/docs/features/themes/).

The only issue I have encountered (so far) is the tiling of the profile picture. I have done some initial digging into the issue and would happily settle on removing the circle-style profile picture if that fixed the issue, but I haven't been able to do that yet.
![image](https://user-images.githubusercontent.com/7396341/230700895-ba310ae3-7935-43db-9f63-c845ffa4ae9e.png)

The glitch theme certainly introduces other changes that make mastodon-bird-ui do some unexpected things, but it does seem to handle itself reasonably well and I haven't seen any visual issues. 

@ronilaukkarinen, if you can point me to where the circle profile picture stuff is and/or any thoughts on it's interaction with glitch-soc, I would appreciate it!

**Comment by ronilaukkarinen** [comment]
Thanks for the issue and thanks for trying out Mastodon Bird UI!

Yeah, there are class changes and other structural changes in glitch-soc and it's a completely separate project so for now I'm not going to support it. However, since you asked for help, let me help real quick.

First, add `.layout-single-column .account__header__bar` under `/* Panels and things that should be transparent */` to get the profile top bar transparent. On glitch-soc the profile picture is a div with background instead of img like on vanilla, so you should look for `/* Avatars */` and replace it like this (it needs `!important` because glitch-soc forces the inline styles 90px x 90px on avatars):

```css
/* Avatars */
.layout-single-column .account__header__bar .avatar .account__avatar,
.layout-single-column .account-card__title__avatar .account__avatar,
.layout-single-column .account-card__title__avatar img,
.layout-single-column .account__avatar > img,
.layout-single-column .column > .scrollable .status__avatar img {
  background-repeat: no-repeat;

  /* Need to override inline styles */
  /* stylelint-disable-next-line */
  background-size: cover !important;
  border: 0;
  border-radius: 50%;
  box-shadow: rgb(255 255 255 / 0.03) 0 0 2px inset;
}
```

...and voilà!

![image](https://user-images.githubusercontent.com/1534150/230741358-790b3f0b-d565-45b8-a2a2-84c3e4449328.png)

However, only the top header styles are not enough, there are lots of other styles to cover as you can see here, many things are off in the posts:

![image](https://user-images.githubusercontent.com/1534150/230741411-56eb37e4-d8f4-4900-b95b-4414bc270cf8.png)

While it might be possible to support both vanilla and glitch-soc at the same time (nothing is impossible if you know CSS like I do heh), I currently have no time to support ecosystems I don't use myself. Hence, I'm going to close this issue. But I hope this gives you and others head start who want to use Mastodon Bird UI with glitch-soc. :+1: :heart:
