### ISSUE TITLE
Missing Active Tab Indicator on Mastodon 4.2.x Instances

### ISSUE THREAD

**Issue by rimar1337** [ronilaukkarinen/mastodon-bird-ui#73]
I was working on my CSS userstyle which is a patch set on top of Mastodon Bird UI when I came across this issue on some mastodon instances. This issue can be seen in the screenshots below:

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/132627503/cff03aa0-a859-41ca-ad41-552e17b7c5e1)

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/132627503/c006e7c2-8544-48b6-9b31-6738d2264571)

From my limited testing, I observed that it only breaks on Mastodon instances on version v4.2.0 or above

On my patch set userstyle, I was able to fix this issue by adding the following CSS code:
```scss
.layout-single-column .account__section-headline a.active::after,
.layout-single-column .account__section-headline button.active::after,
.layout-single-column .notification__filter-bar a.active::after,
.layout-single-column .notification__filter-bar button.active::after {
  content: "";
  display: block;
  bottom: -1px;
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}
```
The fix above is compatible with instances still on Mastodon v4.1.x. However, I'm not entirely certain if this solution is applicable to Mastodon Bird UI.

**Comment by ronilaukkarinen** [comment]
True, something has changed. I missed this. Can you send a PR @rimar1337 so I can directly test it?

**Comment by ronilaukkarinen** [comment]
I have checked the differences now. The new core changed it to ::before instead of ::after:

```css
.account__section-headline a.active:before,
.account__section-headline button.active:before,
.notification__filter-bar a.active:before,
.notification__filter-bar button.active:before {
    background: #8c8dff;
    border-radius: 4px;
    bottom: -1px;
    content: "";
    display: block;
    height: 3px;
    left: 0;
    position: absolute;
    width: 100%;
}
```

I'll make the changes.
